(function(){function h(a){var c={};a=a.split(",");for(var d=0;d<a.length;d++)c[a[d]]=!0;return c}var q=/^<([-A-Za-z0-9_]+)((?:\s+\w+(?:\s*=\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/,t=/^<\/([-A-Za-z0-9_:]+)[^>]*>/,v=/([-A-Za-z0-9_]+)(?:\s*=\s*(?:(?:"((?:\\.|[^"])*)")|(?:'((?:\\.|[^'])*)')|([^>\s]+)))?/g,r=/^<([-A-Za-z0-9_:-]+)((?:\s+[a-zA-Z_0-9:-]+(?:\s*=\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/,w=/([-A-Za-z0-9_:-]+)(?:\s*=\s*(?:(?:"((?:\\.|[^"])*)")|(?:'((?:\\.|[^'])*)')|([^>\s]+)))?/g,
x=h("colgroup,col"),y=h("area,base,basefont,br,col,frame,hr,img,input,isindex,link,meta,param,embed");h("area,base,basefont,br,col,frame,img,input,isindex,link,meta,param,embed");var z=h("address,applet,blockquote,button,center,dd,del,dir,div,dl,dt,fieldset,form,frameset,hr,iframe,ins,isindex,li,map,menu,noframes,noscript,object,ol,p,pre,script,table,tbody,td,tfoot,th,thead,tr,ul,h1,h2,h3,h4,h5,h6"),u=h("a,abbr,acronym,applet,b,basefont,bdo,big,br,button,cite,code,del,dfn,em,font,i,iframe,img,input,ins,kbd,label,map,object,q,s,samp,script,select,small,span,strike,strong,sub,sup,textarea,tt,u,var"),
A=h("colgroup,dd,dt,li,options,p,td,tfoot,th,thead,tr"),B=h("checked,compact,declare,defer,disabled,ismap,multiple,nohref,noresize,noshade,nowrap,readonly,selected"),C=h("");"undefined"==typeof DEXT5_EDITOR&&(DEXT5_EDITOR={});DEXT5_EDITOR.HTMLParser=function(a,c,d){function k(a,b,e,c){b=b.toLowerCase();if(z[b]){for("table"!=f.last()&&"tbody"!=f.last()||"td"!=b||k("","tr","","");f.last()&&u[f.last()];)n("",f.last());"p"!=f.last()||"table"!=b&&"hr"!=b&&"center"!=b||n("","p")}A[b]&&f.last()==b&&n("",
b);(c=y[b]||!!c)||f.push(b);if(d.start){var g=[];a=q.test(a)?v:w;e.replace(a,function(a,b,d,c,k){d=d?d:c?c:k?k:B[b]?b:"";c="";""!=a&&(a=a.substring(a.indexOf(b)+b.length),a=a.substring(a.indexOf("=")+1),a=a.replace(/^\s+/,""),c=a.substring(0,1),"'"!=c&&'"'!=c&&(c=""));g.push({name:b,value:d,escaped:d.replace(/(^|[^\\])"/g,'$1\\"'),quotationmark:c})});d.start&&d.start(b,g,c)}}function n(a,b){if(b)for(b=b.toLowerCase(),c=f.length-1;0<=c&&f[c]!=b;c--);else var c=0;if(0<=c){for(var k=f.length-1;k>=c;k--)d.end&&
d.end(f[k]);f.length=c}}var b,e,f=[],h=a;for(f.last=function(){return this[this.length-1]};a;){e=!0;if(f.last()&&C[f.last()])a=a.replace(new RegExp("(.*)</"+f.last()+"[^>]*>"),function(a,b){b=b.replace(/\x3c!--(.*?)--\x3e/g,"$1").replace(/<!\[CDATA\[(.*?)]]\x3e/g,"$1");d.chars&&d.chars(b);return""}),n("",f.last());else{var g=a.indexOf("<");b=a.indexOf(">")+1;var m=a.substring(g,b);if(0==a.indexOf("\x3c!--"))b=a.indexOf("--\x3e"),0<=b&&(d.comment&&d.comment(a.substring(4,b)),a=a.substring(b+3),e=!1);
else if(0==a.indexOf("<?xml"))b=a.indexOf("/>"),0<=b&&(a=a.substring(b+2),e=!1);else if(0!=a.indexOf("<")&&"</"+f.last()+">"==m.replace(/ /ig,""))e=a.substring(0,g),a=a.substring(b),a=e+"</"+f.last()+">"+a,e=!0;else if(0==a.indexOf("</")){if(b=a.match(t))a=a.substring(b[0].length),b[0].replace(t,n),e=!1}else if(0==a.indexOf("<"))if(b=a.match(q))a=a.substring(b[0].length),b[0].replace(q,k),e=!1;else if(b=a.match(r))a=a.substring(b[0].length),b[0].replace(r,k),e=!1;else if("1"==DEXTTOP.G_CURREDITOR._config.removeIncorrectAttribute&&
(b=a.indexOf("<"),m=a.indexOf(">"),0==b&&0<m)){var l=a.substring(0,m+1),p=g=b=0;0<l.indexOf('\ub9d1\uc740=""')?(b=l.indexOf('\ub9d1\uc740=""'),g=5,p=l.split('\ub9d1\uc740=""').length):0<l.indexOf("\ub9d1\uc740=''")&&(b=l.indexOf("\ub9d1\uc740=''"),g=5,p=l.split("\ub9d1\uc740=''").length);if(2==p&&0<b&&(m=a.substring(m+1),p=l.substring(0,b).lastIndexOf(" "),p<b+g))if(a=l.substring(p,b+g),l=l.replace(a,""),a=l+m,b=a.match(q))a=a.substring(b[0].length),b[0].replace(q,k),e=!1;else if(b=a.match(r))a=a.substring(b[0].length),
b[0].replace(r,k),e=!1}e&&(b=a.indexOf("<"),e=0>b?a:a.substring(0,b),a=0>b?"":a.substring(b),d.chars&&(f.last()&&u[f.last()]&&"textarea"!=f.last()&&"script"!=f.last()&&(b=!1,g=RegExp("\\S\\n","g"),g.test(e)&&(b=!0),g=RegExp("\\n\\S","g"),g.test(e)&&(b=!0),g=RegExp("\\S\\n\\S","g"),g.test(e)&&(b=!0),b?e=e.replace(/\n/g," "):(g=RegExp("\\n\\n","g"),g.test(e)&&""==e.trim()?e=e.replace(/\n\n/g,""):e==unescape("%20%20")&&(b=new RegExp(unescape("%20"),"g"),e=e.replace(b,"&nbsp;")))),c&&(b=new RegExp(unescape("%20%20"),
"g"),e=e.replace(b,"&nbsp; ")),d.chars(e)))}if(a==h)throw"Parse Error: "+a;h=a}n()};DEXT5_EDITOR.HTMLParser.HTMLtoXML=function(a,c){var d="";DEXT5_EDITOR.HTMLParser(a,c,{start:function(a,c,b){d+="<"+a;for(a=0;a<c.length;a++)d="href"==c[a].name||"src"==c[a].name?d+(" "+c[a].name+"="+c[a].quotationmark+c[a].value+c[a].quotationmark):""!=c[a].quotationmark?d+(" "+c[a].name+"="+c[a].quotationmark+c[a].value+c[a].quotationmark):d+(" "+c[a].name+'="'+c[a].escaped+'"');d+=(b?"/":"")+">"},end:function(a){x[a]||
(d+="</"+a+">")},chars:function(a){d+=a},comment:function(a){d="0"==DEXTTOP.G_CURREDITOR._config.removeComment?d+("\x3c!--"+a+"--\x3e"):d+""}});DEXTTOP.DEXT5.util.writeLog("DEBUG","HTMLParser.HTMLtoXML return - "+d,"","");return d};DEXT5_EDITOR.HTMLParser.RemoveOfficeTag=function(a,c){if(""==a||void 0==a)return DEXTTOP.DEXT5.util.writeLog("DEBUG","HTMLParser.RemoveOfficeTag return - ","",""),"";a=DEXT5_EDITOR.HTMLParser.RemoveOfficeTag2(a);a=DEXTTOP.DEXT5.util.replaceOneSpaceToNbsp(a);c&&(a=a.replace(/>\s+</g,
"><"));DEXTTOP.DEXT5.util.writeLog("DEBUG","HTMLParser.RemoveOfficeTag return - "+a,"","");return a};DEXT5_EDITOR.HTMLParser.RemoveOfficeTag2=function(a){var c=RegExp("<o:p></o:p>","gi");a=a.replace(c,"");c=RegExp("<o:p>\\s+</o:p>","gi");a=a.replace(c,"");c=RegExp("<o:p ([^>]+)></o:p>","gi");a=a.replace(c,"");c=RegExp("<o:p ([^>]+)>\\s+</o:p>","gi");a=a.replace(c,"");a=a.replace(/\slang=[\"]?en-us[\"]?/gi,"");"1"==DEXTTOP.G_CURREDITOR._config.removeMsoClass&&(a=a.replace(/\sclass=[\"]?(mso)\w+[\"]?/gi,
""));a=a.replace(/&quot;/gi,"&quot_dext");c=RegExp('mso-[^:]+:[^;">]+;',"gi");a=a.replace(c,"");c=RegExp('mso-[^:]+:[^;">]+("|\')',"gi");a=a.replace(c,"$1");a=a.replace(/&quot_dext/gi,"&quot;");c=RegExp("<v:shapetype ([^>]+)>[\\s\\S]*?</v:shapetype>","gi");a=a.replace(c,"");c=RegExp("<v:shape [^>]+>[\\s\\S]*?(<img [^>]+>)*?</v:shape>","gi");a=a.replace(c,"$1");c=RegExp("<v:shape ([^>]+)>[\\s\\S]*?</v:shape>","gi");a=a.replace(c,"");a=a.replace(/<\!\[if ppt\]>/gi,"");DEXTTOP.DEXT5.util.writeLog("DEBUG",
"HTMLParser.RemoveOfficeTag2 return - "+a,"","");return a};DEXT5_EDITOR.HTMLParser.makeMap=function(a){return h(a)}})();
