/*
 GNU Lesser General Public License, http://www.gnu.org/copyleft/lesser.html
 @author  Jan Odvarko, http://odvarko.cz
 @created 2008-06-15
 @updated 2013-04-08
 @link    http://jscolor.com
*/
Array.prototype.indexOf||(Array.prototype.indexOf=function(c,f){f=f||0;for(var a=this.length;f<a;){if(this[f]===c)return f;++f}return-1});
var jscolor={dir:"../images/editor/jscolor/",bindClass:"color",binding:!0,preloading:!0,clickedElem:null,styleColor:"",actionType:"",excuteFn:null,install:function(){jscolor.addEvent(window,"load",jscolor.init)},init:function(){jscolor.binding&&jscolor.bind();jscolor.preloading&&jscolor.preload()},getDir:function(){if(!jscolor.dir){var c=jscolor.detectDir();jscolor.dir=!1!==c?c:"jscolor/"}return jscolor.dir},detectDir:function(){for(var c=location.href,f=document.getElementsByTagName("base"),a=0;a<
f.length;a+=1)f[a].href&&(c=f[a].href);f=document.getElementsByTagName("script");for(a=0;a<f.length;a+=1)if(f[a].src&&/(^|\/)jscolor\.js([?#].*)?$/i.test(f[a].src))return c=(new jscolor.URI(f[a].src)).toAbsolute(c),c.path=c.path.replace(/[^\/]+$/,""),c.query=null,c.fragment=null,c.toString();return!1},bind:function(){for(var c=new RegExp("(^|\\s)("+jscolor.bindClass+")\\s*(\\{[^}]*\\})?","i"),f=document.getElementsByTagName("div"),a=0;a<f.length;a+=1){var n;if(!f[a].color&&f[a].className&&(n=f[a].className.match(c))){var x=
{};if(n[3])try{x=(new Function("return ("+n[3]+")"))()}catch(G){}f[a].color=new jscolor.color(f[a],x)}}},preload:function(){for(var c in jscolor.imgRequire)jscolor.imgRequire.hasOwnProperty(c)&&jscolor.loadImage(c)},images:{pad:[130,81],sld:[15,81],cross:[20,20],arrow:[3,0]},imgRequire:{},imgLoaded:{},requireImage:function(c){jscolor.imgRequire[c]=!0},loadImage:function(c){jscolor.imgLoaded[c]||(jscolor.imgLoaded[c]=new Image,jscolor.imgLoaded[c].src=jscolor.getDir()+c)},fetchElement:function(c){return"string"===
typeof c?document.getElementById(c):c},addEvent:function(c,f,a){c.addEventListener?c.addEventListener(f,a,!1):c.attachEvent&&c.attachEvent("on"+f,a)},fireEvent:function(c,f){if(c)if(document.createEvent){var a=document.createEvent("HTMLEvents");a.initEvent(f,!0,!0);c.dispatchEvent(a)}else if(document.createEventObject)document.createEventObject();else if(c["on"+f])c["on"+f]()},getElementPos:function(c){var f=c,a=0,n=0;if(f.offsetParent){do a+=f.offsetLeft,n+=f.offsetTop;while(f=f.offsetParent)}for(;(c=
c.parentNode)&&"BODY"!==c.nodeName.toUpperCase();)a-=c.scrollLeft,n-=c.scrollTop;return[a,n]},getElementSize:function(c){return[c.offsetWidth,c.offsetHeight]},getRelMousePos:function(c){var f=0,a=0;c||(c=window.event);"number"===typeof c.offsetX?(f=c.offsetX,a=c.offsetY):"number"===typeof c.layerX&&(f=c.layerX,a=c.layerY);return{x:f,y:a}},getViewPos:function(){return"number"===typeof window.pageYOffset?[window.pageXOffset,window.pageYOffset]:document.body&&(document.body.scrollLeft||document.body.scrollTop)?
[document.body.scrollLeft,document.body.scrollTop]:document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[0,0]},getViewSize:function(){return"number"===typeof window.innerWidth?[window.innerWidth,window.innerHeight]:document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)?[document.documentElement.clientWidth,document.documentElement.clientHeight]:
document.body&&(document.body.clientWidth||document.body.clientHeight)?[document.body.clientWidth,document.body.clientHeight]:[0,0]},URI:function(c){function f(a){for(var c="";a;)if("../"===a.substr(0,3)||"./"===a.substr(0,2))a=a.replace(/^\.+/,"").substr(1);else if("/./"===a.substr(0,3)||"/."===a)a="/"+a.substr(3);else if("/../"===a.substr(0,4)||"/.."===a)a="/"+a.substr(4),c=c.replace(/\/?[^\/]*$/,"");else if("."===a||".."===a)a="";else{var f=a.match(/^\/?[^\/]*/)[0];a=a.substr(f.length);c+=f}return c}
this.authority=this.scheme=null;this.path="";this.fragment=this.query=null;this.parse=function(a){a=a.match(/^(([A-Za-z][0-9A-Za-z+.-]*)(:))?((\/\/)([^\/?#]*))?([^?#]*)((\?)([^#]*))?((#)(.*))?/);this.scheme=a[3]?a[2]:null;this.authority=a[5]?a[6]:null;this.path=a[7];this.query=a[9]?a[10]:null;this.fragment=a[12]?a[13]:null;return this};this.toString=function(){var a="";null!==this.scheme&&(a=a+this.scheme+":");null!==this.authority&&(a=a+"//"+this.authority);null!==this.path&&(a+=this.path);null!==
this.query&&(a=a+"?"+this.query);null!==this.fragment&&(a=a+"#"+this.fragment);return a};this.toAbsolute=function(a){a=new jscolor.URI(a);var c=new jscolor.URI;if(null===a.scheme)return!1;null!==this.scheme&&this.scheme.toLowerCase()===a.scheme.toLowerCase()&&(this.scheme=null);null!==this.scheme?(c.scheme=this.scheme,c.authority=this.authority,c.path=f(this.path),c.query=this.query):(null!==this.authority?(c.authority=this.authority,c.path=f(this.path),c.query=this.query):(""===this.path?(c.path=
a.path,c.query=null!==this.query?this.query:a.query):("/"===this.path.substr(0,1)?c.path=f(this.path):(c.path=null!==a.authority&&""===a.path?"/"+this.path:a.path.replace(/[^\/]+$/,"")+this.path,c.path=f(c.path)),c.query=this.query),c.authority=a.authority),c.scheme=a.scheme);c.fragment=this.fragment;return c};c&&this.parse(c)},color:function(c,f,a,n,x,G){function z(d,a,c){if(null===d)return[c,c,c];var e=Math.floor(d),f=c*(1-a);d=c*(1-a*(e%2?d-e:1-(d-e)));switch(e){case 6:case 0:return[c,d,f];case 1:return[d,
c,f];case 2:return[f,c,d];case 3:return[f,d,c];case 4:return[d,f,c];case 5:return[c,f,d]}}function K(d,c){if(!jscolor.picker){jscolor.picker={box:document.createElement("div"),boxB:document.createElement("div"),pad:document.createElement("div"),padB:document.createElement("div"),padM:document.createElement("div"),sld:document.createElement("div"),sldB:document.createElement("div"),sldM:document.createElement("div"),btn:document.createElement("div"),boxC:document.createElement("div"),boxHEX:document.createElement("span"),
boxRGB:document.createElement("span"),btnS:document.createElement("span"),btnT:document.createTextNode(e.pickerCloseText),select:document.createElement("select"),option1:document.createElement("option"),option2:document.createElement("option"),btnOk:document.createElement("input"),btnCancle:document.createElement("input"),label:document.createElement("label"),labelR:document.createElement("label"),labelG:document.createElement("label"),labelB:document.createElement("label"),lbColor:document.createElement("input"),
lbColor2:document.createElement("input"),lbColorR:document.createElement("input"),lbColorG:document.createElement("input"),lbColorB:document.createElement("input"),inbottom:document.createElement("div"),bottom:document.createElement("div")};for(var a=0;a<jscolor.images.sld[1];a+=4){var f=document.createElement("div");f.style.height="4px";f.style.fontSize="1px";f.style.lineHeight="0";jscolor.picker.sld.appendChild(f)}jscolor.picker.sldB.appendChild(jscolor.picker.sld);jscolor.picker.box.appendChild(jscolor.picker.sldB);
jscolor.picker.box.appendChild(jscolor.picker.sldM);jscolor.picker.padB.appendChild(jscolor.picker.pad);jscolor.picker.box.appendChild(jscolor.picker.padB);jscolor.picker.box.appendChild(jscolor.picker.padM);jscolor.picker.btnS.appendChild(jscolor.picker.btnT);jscolor.picker.btn.appendChild(jscolor.picker.btnS);jscolor.picker.box.appendChild(jscolor.picker.btn);jscolor.picker.boxB.appendChild(jscolor.picker.box);jscolor.picker.boxC.style.margin="0 0 5px 0";jscolor.picker.boxC.style.padding="0";jscolor.picker.boxC.style.textAlign=
"left";jscolor.picker.boxC.style.marginBottom="5px";jscolor.picker.lbColor2.setAttribute("type","text");jscolor.picker.lbColor2.setAttribute("id","cp_lb_color2");jscolor.picker.lbColor2.setAttribute("disabled","disabled");jscolor.picker.lbColor2.style.border="solid 1px #c5c5c5";jscolor.picker.lbColor2.style.width="33px";jscolor.picker.lbColor2.style.backgroundColor="#ffffff";a=19;parent.DEXTTOP.DEXT5.browser.ie&&9>=parent.DEXTTOP.DEXT5.browser.ieVersion&&!parent.DEXTTOP.DEXT5.browser.quirks&&(a=15);
jscolor.picker.lbColor2.style.height=a+"px";jscolor.picker.lbColor2.style.marginLeft="-1px";jscolor.picker.boxHEX.style.display="inline-block";jscolor.picker.boxHEX.style.margin="0";jscolor.picker.boxHEX.style.padding="0";jscolor.picker.label.innerText="#";jscolor.picker.label.style.marginLeft="1px";jscolor.picker.label.style.color="#5d5d5d";jscolor.picker.label.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.label.style.fontSize="13px";jscolor.picker.lbColor.setAttribute("type",
"text");jscolor.picker.lbColor.setAttribute("id","cp_lb_color");jscolor.picker.lbColor.style.border="solid 1px #c5c5c5";jscolor.picker.lbColor.style.color="#5d5d5d";jscolor.picker.lbColor.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.lbColor.style.fontSize="13px";jscolor.picker.lbColor.style.width=parent.DEXTTOP.DEXT5.browser.ie&&9>=parent.DEXTTOP.DEXT5.browser.ieVersion&&!parent.DEXTTOP.DEXT5.browser.quirks?"98px":parent.DEXTTOP.DEXT5.browser.chrome?"108px":"107px";jscolor.picker.lbColor.style.height=
a+"px";jscolor.picker.lbColor.style.imeMode="disabled";jscolor.picker.lbColor.maxLength="6";parent.DEXTTOP.DEXT5.util.addEvent(jscolor.picker.lbColor,"keyup",function(b){try{jscolor.picker.lbColor2.style.backgroundColor="#"+jscolor.picker.lbColor.value}catch(d){jscolor.picker.lbColor2.style.backgroundColor="#ffffff"}});jscolor.picker.boxHEX.appendChild(jscolor.picker.label);jscolor.picker.boxHEX.appendChild(jscolor.picker.lbColor);var f="30px",l="3px";parent.DEXTTOP.DEXT5.browser.ie&&9>=parent.DEXTTOP.DEXT5.browser.ieVersion&&
!parent.DEXTTOP.DEXT5.browser.quirks?(f="25.5px",l=""):parent.DEXTTOP.DEXT5.browser.chrome&&(f="29.5px");jscolor.picker.labelR.innerText="R";jscolor.picker.labelR.style.color="#5d5d5d";jscolor.picker.labelR.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.labelR.style.fontSize="13px";jscolor.picker.labelR.style.marginLeft=l;jscolor.picker.lbColorR.setAttribute("type","text");jscolor.picker.lbColorR.setAttribute("id","cp_lb_color_r");jscolor.picker.lbColorR.style.border="solid 1px #c5c5c5";
jscolor.picker.lbColorR.style.width=f;jscolor.picker.lbColorR.style.height=a+"px";jscolor.picker.lbColorR.style.color="#5d5d5d";jscolor.picker.lbColorR.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.lbColorR.style.fontSize="13px";jscolor.picker.lbColorR.style.imeMode="disabled";jscolor.picker.lbColorR.maxLength="3";parent.DEXTTOP.DEXT5.util.addEvent(jscolor.picker.lbColorR,"keypress",function(b){var d=b.keyCode?b.keyCode:b.which;(48>d||57<d)&&parent.DEXTTOP.DEXT5.util.cancelEvent(b)});
parent.DEXTTOP.DEXT5.util.addEvent(jscolor.picker.lbColorR,"keyup",function(b){17==(b.keyCode?b.keyCode:b.which)&&(ctrlDown=!1);0>jscolor.picker.lbColorR.value?jscolor.picker.lbColorR.value=0:255<jscolor.picker.lbColorR.value?jscolor.picker.lbColorR.value=255:"0"!=jscolor.picker.lbColorR.value&&0==jscolor.picker.lbColorR.value.indexOf("0")&&(jscolor.picker.lbColorR.value=jscolor.picker.lbColorR.value.replace("0",""));try{jscolor.picker.lbColor2.style.backgroundColor="rgb("+jscolor.picker.lbColorR.value+
", "+jscolor.picker.lbColorG.value+", "+jscolor.picker.lbColorB.value+")"}catch(d){jscolor.picker.lbColor2.style.backgroundColor="rgb(255,255,255)"}});jscolor.picker.labelG.innerText="G";jscolor.picker.labelG.style.color="#5d5d5d";jscolor.picker.labelG.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.labelG.style.fontSize="13px";jscolor.picker.lbColorG.setAttribute("type","text");jscolor.picker.lbColorG.setAttribute("id","cp_lb_color_g");jscolor.picker.lbColorG.style.border=
"solid 1px #c5c5c5";jscolor.picker.lbColorG.style.width=f;jscolor.picker.lbColorG.style.height=a+"px";jscolor.picker.lbColorG.style.color="#5d5d5d";jscolor.picker.lbColorG.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.lbColorG.style.fontSize="13px";jscolor.picker.lbColorG.style.imeMode="disabled";jscolor.picker.lbColorG.maxLength="3";parent.DEXTTOP.DEXT5.util.addEvent(jscolor.picker.lbColorG,"keypress",function(b){var d=b.keyCode?b.keyCode:b.which;(48>d||57<d)&&parent.DEXTTOP.DEXT5.util.cancelEvent(b)});
parent.DEXTTOP.DEXT5.util.addEvent(jscolor.picker.lbColorG,"keyup",function(b){0>jscolor.picker.lbColorG.value?jscolor.picker.lbColorG.value=0:255<jscolor.picker.lbColorG.value?jscolor.picker.lbColorG.value=255:"0"!=jscolor.picker.lbColorG.value&&0==jscolor.picker.lbColorG.value.indexOf("0")&&(jscolor.picker.lbColorG.value=jscolor.picker.lbColorG.value.replace("0",""));try{jscolor.picker.lbColor2.style.backgroundColor="rgb("+jscolor.picker.lbColorR.value+", "+jscolor.picker.lbColorG.value+", "+jscolor.picker.lbColorB.value+
")"}catch(d){jscolor.picker.lbColor2.style.backgroundColor="rgb(255,255,255)"}});jscolor.picker.labelB.innerText="B";jscolor.picker.labelB.style.color="#5d5d5d";jscolor.picker.labelB.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.labelB.style.fontSize="13px";jscolor.picker.lbColorB.setAttribute("type","text");jscolor.picker.lbColorB.setAttribute("id","cp_lb_color_b");jscolor.picker.lbColorB.style.border="solid 1px #c5c5c5";jscolor.picker.lbColorB.style.width=f;jscolor.picker.lbColorB.style.height=
a+"px";jscolor.picker.lbColorB.style.color="#5d5d5d";jscolor.picker.lbColorB.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.lbColorB.style.fontSize="13px";jscolor.picker.lbColorB.style.imeMode="disabled";jscolor.picker.lbColorB.maxLength="3";parent.DEXTTOP.DEXT5.util.addEvent(jscolor.picker.lbColorB,"keypress",function(b){var d=b.keyCode?b.keyCode:b.which;(48>d||57<d)&&parent.DEXTTOP.DEXT5.util.cancelEvent(b)});parent.DEXTTOP.DEXT5.util.addEvent(jscolor.picker.lbColorB,
"keyup",function(b){17==(b.keyCode?b.keyCode:b.which)&&(ctrlDown=!1);0>jscolor.picker.lbColorB.value?jscolor.picker.lbColorB.value=0:255<jscolor.picker.lbColorB.value?jscolor.picker.lbColorB.value=255:"0"!=jscolor.picker.lbColorB.value&&0==jscolor.picker.lbColorB.value.indexOf("0")&&(jscolor.picker.lbColorB.value=jscolor.picker.lbColorB.value.replace("0",""));try{jscolor.picker.lbColor2.style.backgroundColor="rgb("+jscolor.picker.lbColorR.value+", "+jscolor.picker.lbColorG.value+", "+jscolor.picker.lbColorB.value+
")"}catch(d){jscolor.picker.lbColor2.style.backgroundColor="rgb(255,255,255)"}});jscolor.picker.boxRGB.style.margin="0";jscolor.picker.boxRGB.style.padding="0";jscolor.picker.boxRGB.appendChild(jscolor.picker.labelR);jscolor.picker.boxRGB.appendChild(jscolor.picker.lbColorR);jscolor.picker.boxRGB.appendChild(jscolor.picker.labelG);jscolor.picker.boxRGB.appendChild(jscolor.picker.lbColorG);jscolor.picker.boxRGB.appendChild(jscolor.picker.labelB);jscolor.picker.boxRGB.appendChild(jscolor.picker.lbColorB);
jscolor.picker.select.name="colorValue";jscolor.picker.select.id="colorValue";jscolor.picker.select.style.border="1px solid #c5c5c5";jscolor.picker.select.style.color="#5d5d5d";jscolor.picker.select.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.select.style.fontSize="13px";jscolor.picker.option1.value="hex";jscolor.picker.option1.innerText="HEX";jscolor.picker.option2.value="rgb";jscolor.picker.option2.innerText="RGB";jscolor.picker.select.appendChild(jscolor.picker.option1);
jscolor.picker.select.appendChild(jscolor.picker.option2);jscolor.picker.btnOk.setAttribute("type","button");jscolor.picker.btnOk.setAttribute("id","cp_btn_ok");jscolor.picker.btnOk.setAttribute("value",parent.DEXTTOP.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.ok);jscolor.picker.btnOk.style.width="42px";jscolor.picker.btnOk.style.color="#5d5d5d";jscolor.picker.btnOk.className="DEXT_fiVe_EdiTor_font";jscolor.picker.btnOk.style.fontSize="13px";jscolor.picker.btnCancle.setAttribute("type","button");
jscolor.picker.btnCancle.setAttribute("id","cp_btn_cancle");jscolor.picker.btnCancle.setAttribute("value",parent.DEXTTOP.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.close);if(a=0==parent.DEXTTOP.DEXT5.UserAgent.os.name.toLowerCase().indexOf("mac")&&"safari"==parent.DEXTTOP.DEXT5.UserAgent.browser.name.toLowerCase())jscolor.picker.btnOk.style.height="24px";parent.DEXTTOP.DEXT5.browser.mobile||a?(jscolor.picker.btnCancle.style.width="40px",a&&(jscolor.picker.btnCancle.style.height="24px")):jscolor.picker.btnCancle.style.width=
parent.DEXTTOP.DEXT5.browser.ie?"54px":"51px";jscolor.picker.btnCancle.style.color="#5d5d5d";jscolor.picker.btnCancle.className="DEXT_fiVe_EdiTor_font";jscolor.picker.btnCancle.style.fontSize="13px";jscolor.picker.boxC.appendChild(jscolor.picker.lbColor2);jscolor.picker.boxC.appendChild(jscolor.picker.boxHEX);jscolor.picker.bottom.appendChild(jscolor.picker.boxC);jscolor.picker.select.onchange=function(){"hex"==jscolor.picker.select.value?(jscolor.picker.lbColor.value="",jscolor.picker.lbColor2.style.backgroundColor=
"#ffffff",jscolor.picker.boxC.removeChild(jscolor.picker.boxRGB),jscolor.picker.boxHEX.style.display="inline-block",jscolor.picker.boxC.appendChild(jscolor.picker.boxHEX),jscolor.picker.lbColor.focus()):"rgb"==jscolor.picker.select.value&&(jscolor.picker.lbColorR.value="",jscolor.picker.lbColorG.value="",jscolor.picker.lbColorB.value="",jscolor.picker.lbColor2.style.backgroundColor="#ffffff",jscolor.picker.boxC.removeChild(jscolor.picker.boxHEX),jscolor.picker.boxRGB.style.display="inline-block",
jscolor.picker.boxC.appendChild(jscolor.picker.boxRGB),jscolor.picker.lbColorR.focus())};jscolor.picker.inbottom.appendChild(jscolor.picker.select);jscolor.picker.inbottom.appendChild(jscolor.picker.btnOk);jscolor.picker.inbottom.appendChild(jscolor.picker.btnCancle);jscolor.picker.bottom.appendChild(jscolor.picker.inbottom);jscolor.picker.boxB.appendChild(jscolor.picker.bottom);jscolor.picker.boxB.setAttribute("id","color_picker")}var b=jscolor.picker;b.box.onmouseup=b.box.onmousedown=function(){u=
!0};b.box.onmousemove=function(b){if(p||q)p&&A(b),q&&B(b),document.selection?document.selection.empty():window.getSelection&&window.getSelection().removeAllRanges(),v()};"ontouchstart"in window&&b.box.addEventListener("touchmove",function(b){var d={offsetX:b.touches[0].pageX-r.X,offsetY:b.touches[0].pageY-r.Y};if(p||q)p&&A(d),q&&B(d),v();b.stopPropagation();b.preventDefault()},!1);b.padM.onmouseup=b.padM.onmouseout=function(){p&&(p=!1,jscolor.fireEvent(m,"change"))};b.padM.onmousedown=function(b){switch(t){case 0:0===
e.hsv[2]&&e.fromHSV(null,null,1);break;case 1:0===e.hsv[1]&&e.fromHSV(null,1,null)}q=!1;p=!0;A(b);v()};"ontouchstart"in window&&b.padM.addEventListener("touchstart",function(b){r={X:b.target.offsetParent.offsetLeft,Y:b.target.offsetParent.offsetTop};this.onmousedown({offsetX:b.touches[0].pageX-r.X,offsetY:b.touches[0].pageY-r.Y})});b.sldM.onmouseup=b.sldM.onmouseout=function(){q&&(q=!1,jscolor.fireEvent(m,"change"))};b.sldM.onmousedown=function(b){p=!1;q=!0;B(b);v()};"ontouchstart"in window&&b.sldM.addEventListener("touchstart",
function(b){r={X:b.target.offsetParent.offsetLeft,Y:b.target.offsetParent.offsetTop};this.onmousedown({offsetX:b.touches[0].pageX-r.X,offsetY:b.touches[0].pageY-r.Y})});a=H(e);b.box.style.width=a[0]+"px";b.box.style.height=a[1]+"px";b.boxB.style.position="absolute";b.boxB.style.clear="both";b.boxB.style.left=d-6+"px";b.boxB.style.top=c+2+"px";b.boxB.style.zIndex=e.pickerZIndex;b.boxB.style.border=e.pickerBorder+"px solid";b.boxB.style.borderColor=e.pickerBorderColor;b.boxB.style.background=e.pickerFaceColor;
b.pad.style.width=jscolor.images.pad[0]+"px";b.pad.style.height=jscolor.images.pad[1]+"px";b.padB.style.position="absolute";b.padB.style.left=e.pickerFace+"px";b.padB.style.top=e.pickerFace+"px";b.padB.style.border=e.pickerInset+"px solid";b.padB.style.borderColor=e.pickerInsetColor;b.padM.style.position="absolute";b.padM.style.left="0";b.padM.style.top="0";b.padM.style.width=e.pickerFace+2*e.pickerInset+jscolor.images.pad[0]+"px";b.padM.style.height=b.box.style.height;b.padM.style.cursor="crosshair";
b.sld.style.overflow="hidden";b.sld.style.width=jscolor.images.sld[0]+"px";b.sld.style.height=jscolor.images.sld[1]+"px";b.sldB.style.display=e.slider?"block":"none";b.sldB.style.position="absolute";b.sldB.style.right=e.pickerFace+"px";b.sldB.style.top=e.pickerFace+"px";b.sldB.style.border=e.pickerInset+"px solid";b.sldB.style.borderColor=e.pickerInsetColor;b.sldM.style.display=e.slider?"block":"none";b.sldM.style.position="absolute";b.sldM.style.right="3px";b.sldM.style.top="0";b.sldM.style.width=
jscolor.images.sld[0]+jscolor.images.arrow[0]+2*e.pickerInset+"px";b.sldM.style.height=b.box.style.height;try{b.sldM.style.cursor="pointer"}catch(g){b.sldM.style.cursor="hand"}b.btn.style.display=e.pickerClosable?"block":"none";b.btn.style.position="absolute";b.btn.style.left=e.pickerFace+"px";b.btn.style.bottom=e.pickerFace+"px";b.btn.style.padding="0 15px";b.btn.style.height="18px";b.btn.style.border=e.pickerInset+"px solid";(function(){var d=e.pickerInsetColor.split(/\s+/);b.btn.style.borderColor=
2>d.length?d[0]:d[1]+" "+d[0]+" "+d[0]+" "+d[1]})();b.btn.style.color=e.pickerButtonColor;b.btn.style.font="12px sans-serif";b.btn.style.textAlign="center";try{b.btn.style.cursor="pointer"}catch(h){b.btn.style.cursor="hand"}b.btn.onmousedown=function(){e.hidePicker()};b.btnS.style.lineHeight=b.btn.style.height;b.btnOk.style.margin="0 2px 0 4px";b.btnOk.onmousedown=function(){var d="",a=b.select.value;if("hex"==a){if(d=b.lbColor.value,null!=d.match(/[^a-f\d]/gi)){alert(parent.DEXTTOP.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.msg);
setTimeout(function(){b.lbColor.focus()},0);return}}else{var c=b.lbColorR.value,e=b.lbColorG.value,d=b.lbColorB.value;if(0>=c.length||null!=c.match(/[^0-9\d]/gi)){alert(parent.DEXTTOP.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.msg);setTimeout(function(){b.lbColorR.focus()},0);return}if(0>=e.length||null!=e.match(/[^0-9\d]/gi)){alert(parent.DEXTTOP.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.msg);setTimeout(function(){b.lbColorG.focus()},0);return}if(0>=d.length||null!=d.match(/[^0-9\d]/gi)){alert(parent.DEXTTOP.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.msg);
setTimeout(function(){b.lbColorB.focus()},0);return}c=parseInt(c,10).toString(16);1==c.length&&(c="0"+c);e=parseInt(e,10).toString(16);1==e.length&&(e="0"+e);d=parseInt(d,10).toString(16);1==d.length&&(d="0"+d);d=c+e+d}d=d.replace("#","");c=d.match(/[a-f\d]/gi);if(0>=d.length||null==c)alert(parent.DEXTTOP.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.msg),"hex"==a?setTimeout(function(){b.lbColor.focus()},0):setTimeout(function(){b.lbColorR.focus()},0);else if(3==c.length&&(d=c[0]+c[0]+c[1]+c[1]+
c[2]+c[2]),3!=c.length&&6!=c.length)alert(parent.DEXTTOP.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.msg),"hex"==a?setTimeout(function(){b.lbColor.focus()},0):setTimeout(function(){b.lbColorR.focus()},0);else if(-1==d.indexOf("#")&&(d="#"+d),7!=d.length)alert(parent.DEXTTOP.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.msg),"hex"==a?setTimeout(function(){b.lbColor.focus()},0):setTimeout(function(){b.lbColorR.focus()},0);else{"#000000"==d&&(d="black");d=d.toLowerCase();parent.DEXTTOP.DEXT5.browser.LocalStorageSupported&&
(a=parent.DEXTTOP.DEXTWIN.localStorage.getItem(parent.DEXTTOP.G_CURREDITOR.recentlyColorName),null!=a?(a=a.split(","),-1!=a.indexOf(d)&&a.splice(a.indexOf(d),1),a.unshift(d),9<a.length&&(a.reverse(),a.shift(),a.reverse()),parent.DEXTTOP.DEXTWIN.localStorage.setItem(parent.DEXTTOP.G_CURREDITOR.recentlyColorName,a)):parent.DEXTTOP.DEXTWIN.localStorage.setItem(parent.DEXTTOP.G_CURREDITOR.recentlyColorName,d));void 0!==jscolor.styleColor||""!==jscolor.styleColor?jscolor.clickedElem.style[jscolor.styleColor]=
d:(a=iframeDoc.createElement("input"),a.type="hidden",a.value=d,a.id="hidden_color",iframeDoc.body.appendChild(a));if(void 0!==jscolor.actionType||""!==jscolor.actionType)"font_color"==jscolor.actionType||"detail_font_color"==jscolor.actionType?parent.command_fontColor(parent.DEXTTOP.G_CURREDITOR.ID,parent.document.getElementById("dext5_design_"+parent.DEXTTOP.G_CURREDITOR.ID),d):"font_bg_color"==jscolor.actionType||"detail_font_bg_color"==jscolor.actionType?parent.command_fontBgColor(parent.DEXTTOP.G_CURREDITOR.ID,
parent.document.getElementById("dext5_design_"+parent.DEXTTOP.G_CURREDITOR.ID),d):"doc_bg_color"==jscolor.actionType?parent.command_docBGColor(parent.DEXTTOP.G_CURREDITOR.ID,parent.document.getElementById("dext5_design_"+parent.DEXTTOP.G_CURREDITOR.ID),d):"cell_bg_color"==jscolor.actionType||"detail_cell_bg_color"==jscolor.actionType?parent.command_cellBGColor(parent.DEXTTOP.G_CURREDITOR.ID,parent.document.getElementById("dext5_design_"+parent.DEXTTOP.G_CURREDITOR.ID),d):"line_color"==jscolor.actionType&&
jscolor.excuteFn&&jscolor.excuteFn();jscolor.clickedElem=null;jscolor.styleColor="";jscolor.actionType="";jscolor.excuteFn=null;parent.document.body.removeChild(parent.document.getElementById("dext_color_back"));parent.document.body.removeChild(parent.document.getElementById("popupCover"))}};b.lbColor2.style.margin="0 2px 0 0";b.bottom.style.margin="0 0 3px 6px";b.btnCancle.onmousedown=function(){jscolor.clickedElem=null;jscolor.styleColor="";jscolor.actionType="";jscolor.excuteFn=null;document.getElementById("color_picker").style.display=
"none";parent.document.getElementById("popupCover").style.height="200px"};switch(t){case 0:var k="hs2.png";break;case 1:k="hv.png"}b.padM.style.backgroundImage="url('"+jscolor.getDir()+"cross.gif')";b.padM.style.backgroundRepeat="no-repeat";b.pad.style.backgroundImage="url('"+jscolor.getDir()+k+"')";b.pad.style.backgroundRepeat="no-repeat";b.pad.style.backgroundPosition="0 0";I();J();jscolor.picker.owner=e;document.getElementsByTagName("body")[0].appendChild(b.boxB);jscolor.picker.lbColor.focus()}
function H(d){return[2*d.pickerInset+2*d.pickerFace+jscolor.images.pad[0]+(d.slider?2*d.pickerInset+2*jscolor.images.arrow[0]+jscolor.images.sld[0]:0),d.pickerClosable?4*d.pickerInset+3*d.pickerFace+jscolor.images.pad[1]+d.pickerButtonHeight:2*d.pickerInset+2*d.pickerFace+jscolor.images.pad[1]]}function I(){switch(t){case 0:var d=1;break;case 1:d=2}var a=Math.round(e.hsv[0]/6*(jscolor.images.pad[0]-1)),d=Math.round((1-e.hsv[d])*(jscolor.images.pad[1]-1));jscolor.picker.padM.style.backgroundPosition=
e.pickerFace+e.pickerInset+a-Math.floor(jscolor.images.cross[0]/2)+"px "+(e.pickerFace+e.pickerInset+d-Math.floor(jscolor.images.cross[1]/2))+"px";a=jscolor.picker.sld.childNodes;switch(t){case 0:for(var c=z(e.hsv[0],e.hsv[1],1),d=0;d<a.length;d+=1)a[d].style.backgroundColor="rgb("+c[0]*(1-d/a.length)*100+"%,"+c[1]*(1-d/a.length)*100+"%,"+c[2]*(1-d/a.length)*100+"%)";break;case 1:var f,l=[e.hsv[2],0,0],d=Math.floor(e.hsv[0]),b=d%2?e.hsv[0]-d:1-(e.hsv[0]-d);switch(d){case 6:case 0:c=[0,1,2];break;
case 1:c=[1,0,2];break;case 2:c=[2,0,1];break;case 3:c=[2,1,0];break;case 4:c=[1,2,0];break;case 5:c=[0,2,1]}for(d=0;d<a.length;d+=1)f=1-1/(a.length-1)*d,l[1]=l[0]*(1-f*b),l[2]=l[0]*(1-f),a[d].style.backgroundColor="rgb("+100*l[c[0]]+"%,"+100*l[c[1]]+"%,"+100*l[c[2]]+"%)"}}function J(){switch(t){case 0:var d=2;break;case 1:d=1}d=Math.round((1-e.hsv[d])*(jscolor.images.sld[1]-1));jscolor.picker.sldM.style.backgroundPosition="0 "+(e.pickerFace+e.pickerInset+d-Math.floor(jscolor.images.arrow[1]/2))+
"px"}function y(){return jscolor.picker&&jscolor.picker.owner===e}function L(){m!==c&&e.importColor()}function A(d){var a=jscolor.getRelMousePos(d);d=a.x-e.pickerFace-e.pickerInset;a=a.y-e.pickerFace-e.pickerInset;switch(t){case 0:e.fromHSV(6/(jscolor.images.pad[0]-1)*d,1-a/(jscolor.images.pad[1]-1),null,C);break;case 1:e.fromHSV(6/(jscolor.images.pad[0]-1)*d,null,1-a/(jscolor.images.pad[1]-1),C)}}function B(d){d=jscolor.getRelMousePos(d).y-e.pickerFace-e.pickerInset;switch(t){case 0:e.fromHSV(null,
null,1-d/(jscolor.images.sld[1]-1),D);break;case 1:e.fromHSV(null,1-d/(jscolor.images.sld[1]-1),null,D)}}function v(){e.onImmediateChange&&("string"===typeof e.onImmediateChange?new Function(e.onImmediateChange):e.onImmediateChange).call(e)}jscolor.clickedElem=a;jscolor.styleColor=n;jscolor.actionType=x;jscolor.excuteFn=G;this.slider=this.caps=this.hash=this.adjust=this.required=!0;this.styleElement=this.valueElement=c;this.onImmediateChange=null;this.hsv=[0,0,1];this.rgb=[1,1,1];this.minH=0;this.maxH=
6;this.minS=0;this.maxS=1;this.minV=0;this.maxV=1;this.pickerOnfocus=!1;this.pickerMode="HSV";this.pickerPosition="bottom";this.pickerSmartPosition=!1;this.pickerButtonHeight=0;this.pickerClosable=!1;this.pickerCloseText="Close";this.pickerButtonColor="ButtonText";this.pickerFace=6;this.pickerFaceColor="ThreeDFace";this.pickerBorder=1;this.pickerBorderColor="ThreeDHighlight ThreeDShadow ThreeDShadow ThreeDHighlight";this.pickerInset=1;this.pickerInsetColor="ThreeDShadow ThreeDShadow ThreeDShadow ThreeDShadow";
this.pickerZIndex=15E3;for(var E in f)f.hasOwnProperty(E)&&(this[E]=f[E]);this.hidePicker=function(){y()&&(delete jscolor.picker.owner,document.getElementsByTagName("body")[0].removeChild(jscolor.picker.boxB))};this.showPicker=function(){if(!y()){var d=jscolor.getElementPos(c),a=jscolor.getElementSize(c),e=jscolor.getViewPos(),f=jscolor.getViewSize(),l=H(this),b,g,h;switch(this.pickerPosition.toLowerCase()){case "left":b=1;g=0;h=-1;break;case "right":b=1;g=0;h=1;break;case "top":b=0;g=1;h=-1;break;
default:b=0,h=g=1}var k=(a[g]+l[g])/2,d=this.pickerSmartPosition?[-e[b]+d[b]+l[b]>f[b]?-e[b]+d[b]+a[b]/2>f[b]/2&&0<=d[b]+a[b]-l[b]?d[b]+a[b]-l[b]:d[b]:d[b],-e[g]+d[g]+a[g]+l[g]-k+k*h>f[g]?-e[g]+d[g]+a[g]/2>f[g]/2&&0<=d[g]+a[g]-k-k*h?d[g]+a[g]-k-k*h:d[g]+a[g]-k+k*h:0<=d[g]+a[g]-k+k*h?d[g]+a[g]-k+k*h:d[g]+a[g]-k-k*h]:[d[b],d[g]+a[g]-k+k*h];K(d[b],d[g])}};this.importColor=function(){m?this.adjust?!this.required&&/^\s*$/.test(m.value)?(m.value="",h.style.backgroundImage=h.jscStyle.backgroundImage,h.style.backgroundColor=
h.jscStyle.backgroundColor,h.style.color=h.jscStyle.color,this.exportColor(w|F)):this.fromString(m.value):this.fromString(m.value,w)||(h.style.backgroundImage=h.jscStyle.backgroundImage,h.style.backgroundColor=h.jscStyle.backgroundColor,h.style.color=h.jscStyle.color,this.exportColor(w|F)):this.exportColor()};this.exportColor=function(d){if(!(d&w)&&m){var a=this.toString(),c=a;this.caps&&(a=a.toUpperCase());null!=jscolor.picker.lbColor&&(jscolor.picker.lbColor.value=a);if(null!=jscolor.picker.lbColorB){a=
c.match(/[a-f\d]/gi);3==a.length&&(c=a[0]+a[0]+a[1]+a[1]+a[2]+a[2]);var a=c.match(/[a-f\d]{2}/gi),c=parseInt(a[0],16),e=parseInt(a[1],16),a=parseInt(a[2],16);jscolor.picker.lbColorR.value=c;jscolor.picker.lbColorG.value=e;jscolor.picker.lbColorB.value=a}}d&F||!h||null==jscolor.picker.lbColor2||(jscolor.picker.lbColor2.style.backgroundColor="#"+this.toString());d&D||!y()||I();d&C||!y()||J()};this.fromHSV=function(a,c,e,f){null!==a&&(a=Math.max(0,this.minH,Math.min(6,this.maxH,a)));null!==c&&(c=Math.max(0,
this.minS,Math.min(1,this.maxS,c)));null!==e&&(e=Math.max(0,this.minV,Math.min(1,this.maxV,e)));this.rgb=z(null===a?this.hsv[0]:this.hsv[0]=a,null===c?this.hsv[1]:this.hsv[1]=c,null===e?this.hsv[2]:this.hsv[2]=e);this.exportColor(f)};this.fromRGB=function(a,c,e,f){null!==a&&(a=Math.max(0,Math.min(1,a)));null!==c&&(c=Math.max(0,Math.min(1,c)));null!==e&&(e=Math.max(0,Math.min(1,e)));a=null===a?this.rgb[0]:a;c=null===c?this.rgb[1]:c;var h=null===e?this.rgb[2]:e,b=Math.min(Math.min(a,c),h);e=Math.max(Math.max(a,
c),h);var g=e-b;0===g?a=[null,0,e]:(a=a===b?3+(h-c)/g:c===b?5+(a-h)/g:1+(c-a)/g,a=[6===a?0:a,g/e,e]);null!==a[0]&&(this.hsv[0]=Math.max(0,this.minH,Math.min(6,this.maxH,a[0])));0!==a[2]&&(this.hsv[1]=null===a[1]?null:Math.max(0,this.minS,Math.min(1,this.maxS,a[1])));this.hsv[2]=null===a[2]?null:Math.max(0,this.minV,Math.min(1,this.maxV,a[2]));a=z(this.hsv[0],this.hsv[1],this.hsv[2]);this.rgb[0]=a[0];this.rgb[1]=a[1];this.rgb[2]=a[2];this.exportColor(f)};this.fromString=function(a,c){var e="More".match(/^\W*([0-9A-F]{3}([0-9A-F]{3})?)\W*$/i);
return e?(6===e[1].length?this.fromRGB(parseInt(e[1].substr(0,2),16)/255,parseInt(e[1].substr(2,2),16)/255,parseInt(e[1].substr(4,2),16)/255,c):this.fromRGB(parseInt(e[1].charAt(0)+e[1].charAt(0),16)/255,parseInt(e[1].charAt(1)+e[1].charAt(1),16)/255,parseInt(e[1].charAt(2)+e[1].charAt(2),16)/255,c),!0):!1};this.toString=function(){return(256|Math.round(255*this.rgb[0])).toString(16).substr(1)+(256|Math.round(255*this.rgb[1])).toString(16).substr(1)+(256|Math.round(255*this.rgb[2])).toString(16).substr(1)};
var e=this,t="hvs"===this.pickerMode.toLowerCase()?1:0,u=!1,m=jscolor.fetchElement(this.valueElement),h=jscolor.fetchElement(this.styleElement),p=!1,q=!1,r={},w=1,F=2,D=4,C=8;jscolor.addEvent(c,"click",function(){e.showPicker()});jscolor.addEvent(c,"blur",function(){u?u=!1:window.setTimeout(function(){u||(m===c&&e.importColor(),e.pickerOnfocus&&e.hidePicker());u=!1},0)});m&&(f=function(){e.fromString(m.value,w);v()},jscolor.addEvent(m,"keyup",f),jscolor.addEvent(m,"input",f),jscolor.addEvent(m,"blur",
L),m.setAttribute("autocomplete","off"));h&&(h.jscStyle={backgroundImage:h.style.backgroundImage,backgroundColor:h.style.backgroundColor,color:h.style.color});switch(t){case 0:jscolor.requireImage("hs2.png");break;case 1:jscolor.requireImage("hv.png")}jscolor.requireImage("cross.gif");jscolor.requireImage("arrow.gif");this.importColor()}};jscolor.install();
